# Generated by Django 6.0.5 on 2026-05-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='cat',
            field=models.CharField(choices=[('py', 'Pythpn'), ('js', 'JavaScript'), ('HC', 'Html&Css'), ('ot', 'Others')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
