# Generated by Django 6.0.5 on 2026-05-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_code_slug_alter_code_cat_alter_code_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='cat',
            field=models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('hc', 'Html&Css'), ('ot', 'Others')], max_length=2, null=True),
        ),
    ]
