# Generated by Django 6.0.5 on 2026-05-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_code_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
