# Generated by Django 6.0.4 on 2026-06-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_para_alter_reaction_author_alter_reaction_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
