# Generated by Django 6.0.4 on 2026-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
